ktor:
  deployment:
    port: 13900
  application:
    modules:
      - ru.endevir.ApplicationKt.module
  database:
    dbname: postgres
    hostname: localhost
    port: 5432
    username: postgres
    password: postgres
